name       : grantleetheme
version    : 23.04.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/grantleetheme-23.04.0.tar.xz : 5c6462d4cb4857460a61db4919081804e2451bc28f43a0b655ea8a37e7ab7395
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - grantlee-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - kservice-devel
rundeps    :
    - devel :
        - grantlee-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
