name       : grantleetheme
version    : 23.04.1
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/grantleetheme-23.04.1.tar.xz : bf8a968b382b57b415d3c71a0d614f42018c2f056a4214b54988ab57f00de1e1
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - grantlee-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - kservice-devel
rundeps    :
    - devel :
        - grantlee-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
