name       : grantleetheme
version    : 17.04.1
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.04.1/src/grantleetheme-17.04.1.tar.xz : c7014480f733b9db59eaf4f1f7b0f410989a75985f399188376af1d2e90a806a
license    : 
     - GPL-2.0
     - LGPL-2.1
component  : desktop.library 
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates.
description: |
      GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
