name       : grantleetheme
version    : 20.12.3
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/grantleetheme-20.12.3.tar.xz : e33dacd0d4e51e69be2590b4916cfcd4db5ad6ce57d4f8d97f6326e4eb2a3a7d
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - grantlee-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - kservice-devel
rundeps    :
    - devel :
        - grantlee-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
