name       : grantleetheme
version    : 18.08.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/grantleetheme-18.08.0.tar.xz : dbd56866c4e80646deb971aceb699186af3b063d76380716cbd512951d0468d6
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
