name       : grantleetheme
version    : 18.12.2
release    : 18
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/grantleetheme-18.12.2.tar.xz : 7c4081724cef375481d7a8657a9010ea28bb8d82d48faedfa7ef84ca38cfc162
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
