name       : grantleetheme
version    : 20.08.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/grantleetheme-20.08.0.tar.xz : 7e86d2f9f5a725f988211f676da2c4191ed6df55418135f3a54da5d687d63e8e
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
