name       : grantleetheme
version    : 19.04.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/grantleetheme-19.04.0.tar.xz : 6896a7e1db662bea03b6bdd9f92214b5fa50dfbebbbaa7b3156ddb87ccd55a3e
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
