name       : grantleetheme
version    : 18.12.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/grantleetheme-18.12.0.tar.xz : fdffe9bbfef0e0f25be1dd3a63073834b58eb598fd156a11239d6f1f3718b8cc
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
