name       : grantleetheme
version    : 22.04.0
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/grantleetheme-22.04.0.tar.xz : 58f45f21e41cf1588478e8b2b23b4e7b89ec34b9a1e64dc0441203c1a930bdd1
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - grantlee-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - kservice-devel
rundeps    :
    - devel :
        - grantlee-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
