name       : grantleetheme
version    : 17.08.3
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/grantleetheme-17.08.3.tar.xz : 372763bc710cdae1e4bf2e4f16757894217d24d32a1c8d38440644acea2b4f7d
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates.
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
