name       : grantleetheme
version    : 17.08.2
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/grantleetheme-17.08.2.tar.xz : 0a961e5462f73aef20e21fb0d9290cbc898ea2b51ae0c0885df8c3094f433dc4
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates.
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
