name       : grantleetheme
version    : 19.04.2
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.2/src/grantleetheme-19.04.2.tar.xz : a1aea33272b52fed6dadc7969265c1b831d6de1207d624ce505826ae012ba52e
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
