name       : grantleetheme
version    : 21.04.3
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/grantleetheme-21.04.3.tar.xz : 2257142b83296580eb0ffd5a600e7d0d3dc922bd746e2a57c8a6e4ad6285c5cd
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - grantlee-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - kservice-devel
rundeps    :
    - devel :
        - grantlee-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
