name       : grantleetheme
version    : 21.04.0
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/grantleetheme-21.04.0.tar.xz : 9afa6d2414a67362f2c86c6d0379375feafa80323e15fd8fd70131a3d589adcb
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - grantlee-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - kservice-devel
rundeps    :
    - devel :
        - grantlee-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
