name       : grantleetheme
version    : 21.08.1
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/grantleetheme-21.08.1.tar.xz : 953eec15e9b47f699d73b1a0346505c4801c1ef5a02ccc3ec8e115b438584c7f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - grantlee-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - kservice-devel
rundeps    :
    - devel :
        - grantlee-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
