name       : grantleetheme
version    : 18.08.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/grantleetheme-18.08.2.tar.xz : 9bc9d10e0a7fe9bc881585e87ecbae1716fc72fa600e8aba35542d6c8964d2ad
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
