name       : grantleetheme
version    : 17.08.1
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/grantleetheme-17.08.1.tar.xz : 89979d34c31160cb5a69a9c80746bee529cbe832c53fde42537df3044c66de50
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing
    sets of templates.
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
