name       : grantleetheme
version    : 21.08.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/grantleetheme-21.08.0.tar.xz : 45c5b4435555d8713bf49133304dadd49be940c4cbdc761be8ac13ad2c275493
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - grantlee-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - kservice-devel
rundeps    :
    - devel :
        - grantlee-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
