name       : grantleetheme
version    : 21.12.1
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/grantleetheme-21.12.1.tar.xz : e222b5ebcc8c8422a2cb6535e4ef4dd8c902dd55852e4dd6400920b561114246
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - grantlee-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - kservice-devel
rundeps    :
    - devel :
        - grantlee-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
