name       : grantleetheme
version    : 23.04.2
release    : 65
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/grantleetheme-23.04.2.tar.xz : cba8b6ea835e560a01ba7382eac4e02c363e33ff71f281cdc6421533c17aec19
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - grantlee-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - kservice-devel
rundeps    :
    - devel :
        - grantlee-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
